version: "3.8"

# Services
services:
  # Nginx Service
  nginx:
    image: nginx:1.18
    ports:
      - 8282:80
    volumes:
      - ./backend/:/var/www/html/
      - ./.docker/nginx/conf.d/php.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - php

  # PHP Service
  php:
    build: ./.docker/php
    volumes:
      - ./backend/:/var/www/html/
    command: sh -c "php ./wsserver.php start -d && php-fpm"    

  # Vue.js 3
  vue:
    build: 
      context: .
      dockerfile: ./.docker/vue/Dockerfile
    ports:
      - "82:80"
